#!/bin/sh
set -eu

project_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

: "${SUPABASE_URL:?Set SUPABASE_URL in the Xcode Cloud workflow environment.}"
: "${SUPABASE_PUBLISHABLE_KEY:?Set SUPABASE_PUBLISHABLE_KEY in the Xcode Cloud workflow environment.}"

case "$SUPABASE_URL" in
    https://*) ;;
    *)
        echo "SUPABASE_URL must use HTTPS." >&2
        exit 1
        ;;
esac

case "$SUPABASE_PUBLISHABLE_KEY" in
    sb_publishable_*) ;;
    sb_secret_*|*service_role*)
        echo "Refusing a server-side Supabase key. Use the publishable key." >&2
        exit 1
        ;;
    *)
        echo "SUPABASE_PUBLISHABLE_KEY must be an sb_publishable_ key." >&2
        exit 1
        ;;
esac

escaped_supabase_url="$(
    printf '%s' "$SUPABASE_URL" | sed 's#://#:/$()/#'
)"
development_team="${APPLE_DEVELOPMENT_TEAM:-Y5DR22VZYA}"
local_config="$project_root/Config/Local.xcconfig"

umask 077
{
    printf '%s\n' '// Generated by ci_post_clone.sh for this Xcode Cloud build.'
    printf 'DEVELOPMENT_TEAM = %s\n' "$development_team"
    printf 'SUPABASE_URL = %s\n' "$escaped_supabase_url"
    printf 'SUPABASE_PUBLISHABLE_KEY = %s\n' "$SUPABASE_PUBLISHABLE_KEY"
} > "$local_config"

if ! command -v xcodegen >/dev/null 2>&1; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "XcodeGen is unavailable and Homebrew is not installed." >&2
        exit 1
    fi
    brew install xcodegen
fi

cd "$project_root"
./Scripts/generate.sh

echo "Prepared the Xcode project and developer snapshot configuration."
